# Generated by Django 4.2 on 2026-02-11 17:54

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='baner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='baner', verbose_name='تصویر')),
                ('active', models.BooleanField(verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='نامک (slug)')),
                ('image', models.ImageField(upload_to='media_category_picture', verbose_name='تصویر دسته\u200cبندی')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات سئو')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام صاحب اثر (مداح یا سخنران)')),
            ],
            options={
                'verbose_name': 'صاحب اثر',
                'verbose_name_plural': 'صاحبان اثر',
            },
        ),
        migrations.CreateModel(
            name='style_media_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام سبک فایل')),
            ],
            options={
                'verbose_name': 'سبک فایل ',
                'verbose_name_plural': 'سبک های فایل ',
            },
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثلاً: دهه اول ماه محرم 1404', max_length=200, verbose_name='عنوان مناسبت')),
                ('year', models.IntegerField(verbose_name='سال')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='نامک (slug)')),
                ('image', models.ImageField(default='null', upload_to='media_night', verbose_name='تصویر مناسبت')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات سئو')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occasions', to='website.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'مناسبت',
                'verbose_name_plural': 'مناسبت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Night',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='شماره شب')),
                ('slug', models.CharField(help_text='این فیلد به عنوان نام شب در کد استفاده می\u200cشود', max_length=100, unique=True, verbose_name='نامک (slug)')),
                ('image', models.ImageField(default='null', upload_to='media_night', verbose_name='تصویر شب')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات سئو')),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nights', to='website.occasion', verbose_name='مناسبت')),
            ],
            options={
                'verbose_name': 'شب',
                'verbose_name_plural': 'شب\u200cها',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/', verbose_name='فایل ')),
                ('media_type', models.CharField(choices=[('audio', 'صوتی'), ('video', 'ویدئویی')], max_length=10, verbose_name='نوع مدیا')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان فایل')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='نامک (slug)')),
                ('image', models.ImageField(default='null', upload_to='media_night', verbose_name='تصویر نمایه')),
                ('date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('Selected', models.BooleanField(blank=True, null=True, verbose_name='نمایش در صفحه اصلی')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات سئو')),
                ('night', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='website.night', verbose_name='شب')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.owner', verbose_name='صاحب اثر')),
                ('style_media_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.style_media_file', verbose_name='سبک مدیا(سخنرانی،زمینه،شور...)')),
            ],
            options={
                'verbose_name': 'فایل رسانه\u200cای',
                'verbose_name_plural': 'فایل\u200cهای رسانه\u200cای',
            },
        ),
        migrations.CreateModel(
            name='clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='تیتر')),
                ('file', models.FileField(upload_to='media/', verbose_name='فایل ')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(default='null', upload_to='media_night', verbose_name='تصویر نمایه')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات سئو')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.owner', verbose_name='صاحب اثر')),
            ],
            options={
                'verbose_name': ' کلیپ',
                'verbose_name_plural': ' کلیپ ها',
            },
        ),
    ]
