# Generated by Django 4.2 on 2025-10-19 19:33

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='mediafile',
            options={'verbose_name': 'فایل رسانه\u200cای', 'verbose_name_plural': 'فایل\u200cهای رسانه\u200cای'},
        ),
        migrations.AlterModelOptions(
            name='night',
            options={'verbose_name': 'شب', 'verbose_name_plural': 'شب\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='occasion',
            options={'verbose_name': 'مناسبت', 'verbose_name_plural': 'مناسبت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'صاحب اثر', 'verbose_name_plural': 'صاحبان اثر'},
        ),
        migrations.AlterModelOptions(
            name='style_media_file',
            options={'verbose_name': 'سبک فایل ', 'verbose_name_plural': 'سبک های فایل '},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='media_category_picture', verbose_name='تصویر دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سئو'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=100, verbose_name='نامک (slug)'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='Selected',
            field=models.BooleanField(blank=True, null=True, verbose_name='نمایش در صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to='media/', verbose_name='فایل '),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='image',
            field=models.ImageField(default='null', upload_to='media_night', verbose_name='تصویر نمایه'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='media_type',
            field=models.CharField(choices=[('audio', 'صوتی'), ('video', 'ویدئویی')], max_length=10, verbose_name='نوع مدیا'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سئو'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='night',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='website.night', verbose_name='شب'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.owner', verbose_name='صاحب اثر'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='slug',
            field=models.CharField(max_length=100, verbose_name='نامک (slug)'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='style_media_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.style_media_file', verbose_name='سبک مدیا(سخنرانی،زمینه،شور...)'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان فایل'),
        ),
        migrations.AlterField(
            model_name='night',
            name='image',
            field=models.ImageField(default='null', upload_to='media_night', verbose_name='تصویر شب'),
        ),
        migrations.AlterField(
            model_name='night',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سئو'),
        ),
        migrations.AlterField(
            model_name='night',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AlterField(
            model_name='night',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره شب'),
        ),
        migrations.AlterField(
            model_name='night',
            name='occasion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nights', to='website.occasion', verbose_name='مناسبت'),
        ),
        migrations.AlterField(
            model_name='night',
            name='slug',
            field=models.CharField(help_text='این فیلد به عنوان نام شب در کد استفاده می\u200cشود', max_length=100, verbose_name='نامک (slug)'),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occasions', to='website.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='image',
            field=models.ImageField(default='null', upload_to='media_night', verbose_name='تصویر مناسبت'),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سئو'),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='name',
            field=models.CharField(help_text='مثلاً: دهه اول ماه محرم 1404', max_length=200, verbose_name='عنوان مناسبت'),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='slug',
            field=models.CharField(max_length=100, verbose_name='نامک (slug)'),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='year',
            field=models.IntegerField(verbose_name='سال'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام صاحب اثر (مداح یا سخنران)'),
        ),
        migrations.AlterField(
            model_name='style_media_file',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام سبک فایل'),
        ),
        migrations.CreateModel(
            name='clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='media/', verbose_name='فایل ')),
                ('slug', models.CharField(max_length=50)),
                ('image', models.ImageField(default='null', upload_to='media_night', verbose_name='تصویر نمایه')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات سئو')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.owner', verbose_name='صاحب اثر')),
            ],
        ),
    ]
