# Generated by Django 4.2 on 2026-02-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=100, verbose_name='نامک (slug)'),
        ),
        migrations.AlterField(
            model_name='clip',
            name='slug',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='slug',
            field=models.CharField(max_length=100, verbose_name='نامک (slug)'),
        ),
        migrations.AlterField(
            model_name='night',
            name='slug',
            field=models.CharField(help_text='این فیلد به عنوان نام شب در کد استفاده می\u200cشود', max_length=100, verbose_name='نامک (slug)'),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='slug',
            field=models.CharField(max_length=100, verbose_name='نامک (slug)'),
        ),
    ]
