# Generated by Django 4.2 on 2026-02-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_category_options_alter_mediafile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='baner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='baner', verbose_name='تصویر')),
                ('active', models.BooleanField(verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
            },
        ),
        migrations.AlterModelOptions(
            name='clip',
            options={'verbose_name': ' کلیپ', 'verbose_name_plural': ' کلیپ ها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='نامک (slug)'),
        ),
        migrations.AlterField(
            model_name='clip',
            name='name',
            field=models.CharField(max_length=50, verbose_name='تیتر'),
        ),
        migrations.AlterField(
            model_name='clip',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='نامک (slug)'),
        ),
        migrations.AlterField(
            model_name='night',
            name='slug',
            field=models.CharField(help_text='این فیلد به عنوان نام شب در کد استفاده می\u200cشود', max_length=100, unique=True, verbose_name='نامک (slug)'),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='نامک (slug)'),
        ),
    ]
