# Generated by Django 4.2 on 2026-06-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_category_slug_alter_clip_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='live_key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
            ],
        ),
    ]
