# Generated by Django 4.2 on 2026-06-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_live_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='live_key',
        ),
    ]
