# Generated by Django 4.2 on 2026-02-26 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یک\u200cشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='facility_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('video_file', models.FileField(null=True, upload_to='videos/')),
                ('price', models.IntegerField(help_text='قیمت پایه رزرو سالن به تومان', null=True)),
                ('type_hall', models.CharField(choices=[('salonejtemaat', 'سالن اجتماعات'), ('sahne_asli', 'صحن اصلی')], default='salonejtemaat', max_length=50)),
                ('facilities', models.ManyToManyField(blank=True, related_name='halls', to='rezervation.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('cancelled', 'لغو شده')], default='pending', max_length=10)),
                ('type_of_rezerve', models.CharField(choices=[('khatm_sevom&haftom', 'ختم(مراسم سوم و هفتم)'), ('khatm_chehelom', 'ختم(مراسم چهلم)'), ('khatm_chehelom', 'ختم(سالگرد)'), ('amozesh_confrince', 'آموزش_کنفرانس'), ('valime', 'ولیمه')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezervation.hall')),
                ('available_time', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rezervation.availabletime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_profile.mosque_customer')),
            ],
        ),
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('rigen', models.TextField()),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='mosques/logos/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('facilities', models.ManyToManyField(blank=True, related_name='mosques', to='rezervation.facility')),
            ],
        ),
        migrations.CreateModel(
            name='HallImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='halls/images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rezervation.hall')),
            ],
        ),
        migrations.AddField(
            model_name='hall',
            name='mosque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='rezervation.mosque'),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='Hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='rezervation.hall'),
        ),
    ]
