# Generated by Django 4.2 on 2026-02-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
