# Generated by Django 4.2 on 2026-06-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0004_remove_mosque_customer_mosque_and_more'),
        ('rezervation', '0002_alter_hall_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='mosque',
        ),
        migrations.RemoveField(
            model_name='hallimage',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='mosque',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Hall',
        ),
        migrations.RemoveField(
            model_name='order',
            name='available_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='AvailableTime',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='Hall',
        ),
        migrations.DeleteModel(
            name='HallImage',
        ),
        migrations.DeleteModel(
            name='Mosque',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
