# Generated by Django 4.2 on 2026-02-26 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_profile', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rezervation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque_operator',
            name='mosque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezervation.mosque'),
        ),
        migrations.AddField(
            model_name='mosque_operator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mosque_customer',
            name='mosque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezervation.mosque'),
        ),
        migrations.AddField(
            model_name='mosque_customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='my_user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='my_user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
