# Generated by Django 4.2 on 2026-06-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0003_alter_my_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mosque_customer',
            name='mosque',
        ),
        migrations.RemoveField(
            model_name='mosque_customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mosque_operator',
            name='mosque',
        ),
        migrations.RemoveField(
            model_name='mosque_operator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='my_user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='my_user',
            name='user_permissions',
        ),
    ]
