# Generated by Django 4.2 on 2026-06-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezervation', '0003_remove_hall_facilities_remove_hall_mosque_and_more'),
        ('my_profile', '0004_remove_mosque_customer_mosque_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mosque_customer',
        ),
        migrations.DeleteModel(
            name='Mosque_operator',
        ),
        migrations.DeleteModel(
            name='My_user',
        ),
    ]
